export const fakeVendor = [
  {
    name: "1",
    type: "vendor",
    totalSpend: 1000,
    status: "active",
    countryOfRegistration: "Vietnam",
    companyRegistrationNumber: "84",
    qualified: "Yes",
    companyWebsite: "haha.com",
    internalRepresentative: "unknown",
    relationshipSince: "2020",
    currentContact: "Myself",
    mainContactPerson: "Myself",
    officialEmail: "a@gmail.com",
    secondaryEmail: "1@gmail.com",
    mobileNumber: "123456789",
  },

  {
    name: "2",
    type: "vendor",
    totalSpend: 1000,
    status: "active",
    countryOfRegistration: "Vietnam",
    companyRegistrationNumber: "84",
    qualified: "Yes",
    companyWebsite: "haha.com",
    internalRepresentative: "unknown",
    relationshipSince: "2020",
    currentContact: "Boo",
    mainContactPerson: "Boom",
    officialEmail: "b@gmail.com",
    secondaryEmail: "2@gmail.com",
    mobileNumber: "123456789",
  },
];

export const fakeContract = [
  {
    contractNumber: "3",
    contractMemberCorrect: "what",
    product: "hummm",
    title: "Guess what",
    contract: "huh",
    vendor: "me",
    type: "ohh",
  },
  {
    contractNumber: "4",
    contractMemberCorrect: "wwhuttt",
    product: "haaaaa",
    title: "That's right",
    contract: "huh",
    vendor: "me",
    type: "ohh",
  },
];
